name: Build & Deploy to Firebase Hosting

on:
  push:
    branches:
      - main    # ← deploys whenever you push or merge into main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          # Default GitHub token for triggering PR previews (if you use them)
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # 🔑 This must match the secret the CLI created:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIBPROJECT_D71AF }}
          # 'live' means your production channel (your‐id.web.app)
          channelId: live
